Update and rename file_splitting.go to file_splitting.go
camachojua/diplomado-ia pull request #11
Opened 2024-08-29 03:27 UTC by Adrian-Sandwich

2024-08-29 14:33 UTC, camachojua commented
¿Por qué borraste el archivo `file_splitting.go` :thinking: ? Déjalo ahí donde estaba para que los demás compañeros puedan saber la firma de la función que necesitan implemnetar.

2024-08-29 15:26 UTC, Adrian-Sandwich commented
Perdon, es la primera ves que uso git :'v

2024-08-29 15:40 UTC, Adrian-Sandwich commented
hola @camachojua, estoy un poco confundido, borré el archivo file_splitting.go2, pero lo sigo viendo en la capeta movielens, la verdad no se bien que pasó, igual una disculpa de antemano.

Según yo solo hice fork sobre el directorio donde tenemos que poner nuestra solución 

![Ec5NHyiXYAEpAxp](https://github.com/user-attachments/assets/4bfda2ac-def5-40a2-a112-089fb133d89f)

2024-08-29 16:03 UTC, camachojua requested changes
Para que esto vuelva a la vida tienes que ejecutar:

```bash
git restore go/src/student_submissions/movielens/file_splitting.go
```

2024-08-29 21:11 UTC, Adrian-Sandwich commented
creo que ya quedó

2024-08-29 21:28 UTC, camachojua commented
Sólo te falta empujar tu cambio para que se vea reflejado, ya que en este pull request está el código de ayer
![image](https://github.com/user-attachments/assets/0c9f86e7-e803-4fe4-b11f-a5dc7437f9d7)

2024-08-30 00:25 UTC, camachojua commented
Igual lo mejor es que abras otro pull request con tus cambios, si modificar este se te complica

2024-09-20 21:56 UTC, closed without merging